### ISSUE TITLE
IUnlockedStateStore.Items return Dictionary<.. which throws KeyNotFoundException

### ISSUE THREAD

**Issue by mms-** [efaruk/playground#1]
While you can say this is good, it doesn't fit with how the built in Session object works and so requires unnecessary code changes to use the new store.

Maybe return a Dictionary derived class which returns null..

**Comment by efaruk** [comment]
Hi mms,

    This project is a not replacement of standard session, because of the limitations (IIS Session Module level lock.) and standard session module not act as performance optimized.

Our project very optimized for performance; It gets only one time session variables on request start and sets only one time after view render complete. So it requires code changes. If you want to handle millions of users or wanna be scalable for more, you always need some advanced techniques...

I'm sorry if there is a miss understanding, but Unlocked is not a very simple component to implement...

**Comment by efaruk** [comment]
Would you need any assistance? If not, I'm going to close this issue...
