### ISSUE TITLE
Don't create a cookie unless session state is actually used.

### ISSUE THREAD

**Issue by mms-** [efaruk/playground#2]
This is what the default session providers do, no need to freeze the session id and create a cookie if no data was written to the session. i.e. only add the cookie if data exists on request/action end.

Also there is a typo:
if (string.IsNullOrWhiteSpace(configuration.AccessKey)) 
should be
if (!string.IsNullOrWhiteSpace(configuration.AccessKey))

**Comment by efaruk** [comment]
Thank you for reporting my typo ;) I will immediately fix that
You can manage Auto Session Cookie Creation by setting Auto to false 

    &lt;add key=&quot;Unlocked:Auto&quot; value=&quot;false&quot; /&gt;

But you should set to start your session your self by calling 

    UnlockedExtensions.StartSessionIfNew();

But you have mistaken; Default session provider always set ASP.Net_SessionId cookie on every request with new value if you not set any key to session. When you set a value to session session id will not renew any more. You can test it...

Thank you so much for your feedbacks...

**Comment by efaruk** [comment]
Would you need any assistance? If not, I'm going to close this issue...
