### ISSUE TITLE
how to use unlockedStateProvider.Redis with spring? 

### ISSUE THREAD

**Issue by shobhaharmukh** [efaruk/playground#3]
we are using it in conjuction with Spring.net. but store object is null most of the time. i have followed step by step described by you on your post . please let me know if i need to do anything extra.
Thanks,
Shobha

**Comment by efaruk** [comment]
Hi did you check the demo project?

**Comment by shobhaharmukh** [comment]
yes i did.

**Comment by efaruk** [comment]
Did demo project work for you? (Did you configured your redis host in config file)
Attribute is just MVC ActionFilter so, It should work. If you can reproduce this issue in a small project or git repository, I can happily assist you in this...
